# Generated by Django 3.1.7 on 2021-04-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourcart', '0002_auto_20210425_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
