# Generated by Django 3.1.7 on 2021-05-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourcart', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
